v1:
- lib/src/service/v1/**/*

v2:
- lib/src/service/v2/**/*

client:
- lib/src/core/client/*.dart

service/accounts:
- lib/src/service/v1/accounts/*.dart
- lib/src/service/v2/accounts/*.dart
service/admin:
- lib/src/service/v1/admin/*.dart
- lib/src/service/v2/admin/*.dart
service/announcements:
- lib/src/service/v1/announcements/*.dart
- lib/src/service/v2/announcements/*.dart
service/apps:
- lib/src/service/v1/apps/*.dart
- lib/src/service/v2/apps/*.dart
service/instance:
- lib/src/service/v1/instance/*.dart
- lib/src/service/v2/instance/*.dart
service/notifications:
- lib/src/service/v1/notifications/*.dart
- lib/src/service/v2/notifications/*.dart
service/oembed:
- lib/src/service/v1/oembed/*.dart
- lib/src/service/v2/oembed/*.dart
service/proofs:
- lib/src/service/v1/proofs/*.dart
- lib/src/service/v2/proofs/*.dart
service/search:
- lib/src/service/v1/search/*.dart
- lib/src/service/v2/search/*.dart
service/statuses:
- lib/src/service/v1/statuses/*.dart
- lib/src/service/v2/statuses/*.dart
service/timelines:
- lib/src/service/v1/timelines/*.dart
- lib/src/service/v2/timelines/*.dart

test:
- test/**/*.dart

documentation:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- SECURITY.md
- STYLEGUIDE.md
